version: '3.8'
services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/jenkins_home:/var/jenkins_home # Usa o disco persistente para Jenkins
    environment:
      - JAVA_OPTS=-Xmx1024m
      - JENKINS_OPTS=--prefix=/jenkins
    command: >
      java -jar /usr/share/jenkins/jenkins.war
    networks:
      - jenkins_net

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    ports:
      - "8081:8081" # Porta padrão do Nexus
    volumes:
      - /var/nexus-data:/nexus-data # Diretório persistente para Nexus
    environment:
      - NEXUS_CONTEXT=/nexus
    networks:
      - jenkins_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - jenkins_net

volumes:
  jenkins_home:
  nexus_data:

networks:
  jenkins_net: