version: '3.8'
services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /mnt/data/jenkins_home:/var/jenkins_home #Mapeia o disco persistente para o diretório do Jenkins
    environment:
      - JAVA_OPTS=-Xmx1024m
      - JENKINS_OPTS=--prefix=/jenkins
    command: >
      java -jar /usr/share/jenkins/jenkins.war
    networks:
      - jenkins_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - jenkins_net

volumes:

networks:
  jenkins_net: