version: '3.8'
services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Xmx1024m
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
